from _typeshed import Incomplete
from rdkit import Chem as Chem

from .charge import ACID_BASE_PAIRS as ACID_BASE_PAIRS
from .charge import CHARGE_CORRECTIONS as CHARGE_CORRECTIONS
from .charge import Reionizer as Reionizer
from .charge import Uncharger as Uncharger
from .fragment import PREFER_ORGANIC as PREFER_ORGANIC
from .fragment import FragmentRemover as FragmentRemover
from .fragment import LargestFragmentChooser as LargestFragmentChooser
from .metal import MetalDisconnector as MetalDisconnector
from .normalize import MAX_RESTARTS as MAX_RESTARTS
from .normalize import NORMALIZATIONS as NORMALIZATIONS
from .normalize import Normalizer as Normalizer
from .tautomer import MAX_TAUTOMERS as MAX_TAUTOMERS
from .tautomer import TAUTOMER_SCORES as TAUTOMER_SCORES
from .tautomer import TAUTOMER_TRANSFORMS as TAUTOMER_TRANSFORMS
from .tautomer import TautomerCanonicalizer as TautomerCanonicalizer
from .tautomer import TautomerEnumerator as TautomerEnumerator
from .utils import memoized_property as memoized_property

log: Incomplete

class Standardizer:
    normalizations: Incomplete
    acid_base_pairs: Incomplete
    charge_corrections: Incomplete
    tautomer_transforms: Incomplete
    tautomer_scores: Incomplete
    max_restarts: Incomplete
    max_tautomers: Incomplete
    prefer_organic: Incomplete
    def __init__(
        self,
        normalizations=...,
        acid_base_pairs=...,
        charge_corrections=...,
        tautomer_transforms=...,
        tautomer_scores=...,
        max_restarts=...,
        max_tautomers=...,
        prefer_organic=...,
    ) -> None: ...
    def __call__(self, mol): ...
    def standardize(self, mol): ...
    def tautomer_parent(self, mol, skip_standardize: bool = ...): ...
    def fragment_parent(self, mol, skip_standardize: bool = ...): ...
    def stereo_parent(self, mol, skip_standardize: bool = ...): ...
    def isotope_parent(self, mol, skip_standardize: bool = ...): ...
    def charge_parent(self, mol, skip_standardize: bool = ...): ...
    def super_parent(self, mol, skip_standardize: bool = ...): ...
    def standardize_with_parents(self, mol): ...
    def disconnect_metals(self): ...
    def normalize(self): ...
    def reionize(self): ...
    def uncharge(self): ...
    def remove_fragments(self): ...
    def largest_fragment(self): ...
    def enumerate_tautomers(self): ...
    def canonicalize_tautomer(self): ...

def standardize_smiles(smiles): ...
def enumerate_tautomers_smiles(smiles): ...
def canonicalize_tautomer_smiles(smiles): ...
