"""
rdkit.Chem.FeatMaps.FeatMapParser module¶
"""
from _typeshed import Incomplete
from rdkit import Geometry as Geometry
from rdkit.Chem.FeatMaps import FeatMapPoint as FeatMapPoint
from rdkit.Chem.FeatMaps import FeatMaps as FeatMaps

class FeatMapParser(object):
    data: None = ...

    def __init__(
        self, file: Incomplete | None = ..., data: Incomplete | None = ...
    ) -> None: ...
    def SetData(self, data): ...
    def Parse(self, featMap=None): ...
    def ParseFeatPointBlock(self): ...
    def ParseParamBlock(self): ...
    def SetData(self, data): ...
    def ParseFeatPointBlock(self): ...

class FeatMapParseError(ValueError):
    ...
    ...

class FeatMapParser(object):
    data: None = ...

    def __init__(
        self, file: Incomplete | None = ..., data: Incomplete | None = ...
    ) -> None: ...
    def SetData(self, data): ...
    def Parse(self, featMap=None): ...
    def ParseFeatPointBlock(self): ...
    def ParseParamBlock(self): ...
    def SetData(self, data): ...
    def ParseFeatPointBlock(self): ...
