"""
rdkit.RDLogger module¶
"""
from rdkit.rdBase import AttachFileToLog as AttachFileToLog
from rdkit.rdBase import DisableLog as DisableLog
from rdkit.rdBase import EnableLog as EnableLog
from rdkit.rdBase import LogMessage as LogMessage

DEBUG: int
INFO: int
WARNING: int
ERROR: int
CRITICAL: int

class logger(object):
    def critical(self, msg, *args, **kwargs): ...
    def logIt(self, dest, msg, *args, **kwargs): ...
    def debug(self, msg, *args, **kwargs): ...
    def error(self, msg, *args, **kwargs): ...
    def info(self, msg, *args, **kwargs): ...
    def logIt(self, dest, msg, *args, **kwargs): ...
    def setLevel(self, val): ...
    def warning(self, msg, *args, **kwargs): ...
    def critical(self, msg, *args, **kwargs): ...
    def setLevel(self, val): ...
