"""
rdkit.Chem.FragmentCatalog module¶
"""
import _io
from _typeshed import Incomplete
from rdkit import Chem as Chem
from rdkit.Chem.rdfragcatalog import *

def message(self, msg, dest: _io.TextIOWrapper = ...): ...

class BitGainsInfo(object):
    id: int = ...
    description: str = ...
    gain: float = ...
    id: int = ...
    nPerClass: None = ...

def ProcessGainsFile(self, fileName, nToDo=-1, delim=",", haveDescriptions=1): ...
def BuildAdjacencyList(self, catalog, bits, limitInclusion=1, orderLevels=0): ...
def GetMolsMatchingBit(self, mols, bit, fps): ...
def ProcessGainsFile(self, fileName, nToDo=-1, delim=",", haveDescriptions=1): ...
def message(self, msg, dest: _io.TextIOWrapper = ...): ...
