"""
rdkit.Chem.FunctionalGroups module¶
"""
from _typeshed import Incomplete
from rdkit import Chem as Chem
from rdkit import RDConfig as RDConfig

class FGHierarchyNode(object):
    children: None = ...
    label: str = ...
    name: str = ...
    parent: None = ...
    label: str = ...
    pattern: None = ...
    removalReaction: None = ...
    rxnSmarts: str = ...
    smarts: str = ...
    rxnSmarts: str = ...
    parent: None = ...
    removalReaction: None = ...

    def __init__(
        self,
        name,
        patt,
        smarts: str = ...,
        label: str = ...,
        rxnSmarts: str = ...,
        parent: Incomplete | None = ...,
    ) -> None: ...
    def __len__(self) -> int: ...

class FuncGroupFileParseError(ValueError):
    ...
    ...

groupDefns: Incomplete
hierarchy: Incomplete
lastData: Incomplete
lastFilename: Incomplete

def BuildFuncGroupHierarchy(self, fileNm=None, data=None, force=False): ...
def CreateMolFingerprint(self, mol, hierarchy): ...
