"""
rdkit.Chem.QED module¶
QED stands for quantitative estimation of drug-likeness and the concept was for the first time
introduced by Richard Bickerton and coworkers [1]. The empirical rationale of the QED measure
reflects the underlying distribution of molecular properties including molecular weight, logP,
topological polar surface area, number of hydrogen bond donors and acceptors, the number of
aromatic rings and rotatable bonds, and the presence of unwanted chemical functionalities.
The QED results as generated by the RDKit-based implementation of Biscu-it(tm) are not completely
identical to those from the original publication [1]. These differences are a consequence of
differences within the underlying calculated property calculators used in both methods. For
example, discrepancies can be noted in the results from the logP calculations, nevertheless
despite the fact that both approaches (Pipeline Pilot in the original publication and RDKit
in our Biscu-it(tm) implementation) mention to use the Wildman and Crippen methodology for the
calculation of their logP-values [2]. However, the differences in the resulting QED-values
are very small and are not compromising the usefulness of using Qed in your daily research.

[1] Bickerton, G.R.; Paolini, G.V.; Besnard, J.; Muresan, S.; Hopkins, A.L. (2012)‘Quantifying the chemical beauty of drugs’,
Nature Chemistry, 4, 90-98 [https://doi.org/10.1038/nchem.1243]

[2] Wildman, S.A.; Crippen, G.M. (1999)‘Prediction of Physicochemical Parameters by Atomic Contributions’,
Journal of Chemical Information and Computer Sciences, 39, 868-873 [https://doi.org/10.1021/ci990307l]
"""
from typing import NamedTuple, _Alias

from _typeshed import Incomplete
from rdkit import Chem as Chem
from rdkit.Chem import Crippen as Crippen
from rdkit.Chem import MolSurf as MolSurf
from rdkit.Chem.ChemUtils.DescriptorUtilities import (
    setDescriptorVersion as setDescriptorVersion,
)

class ADSparameter(tuple):
    """
    Create new instance of ADSparameter(A, B, C, D, E, F, DMAX)"""

    A: _Alias = ...
    B: _Alias = ...
    C: _Alias = ...
    D: _Alias = ...
    DMAX: _Alias = ...
    E: _Alias = ...
    F: _Alias = ...
    DMAX: _Alias = ...

class QEDproperties(tuple):
    """
    Create new instance of QEDproperties(MW, ALOGP, HBA, HBD, PSA, ROTB, AROM, ALERTS)
    """

    ALERTS: _Alias = ...
    MW: _Alias = ...
    ALOGP: _Alias = ...
    AROM: _Alias = ...
    HBA: _Alias = ...
    HBD: _Alias = ...
    MW: _Alias = ...
    PSA: _Alias = ...
    ROTB: _Alias = ...
    AROM: _Alias = ...
    ALERTS: _Alias = ...

class ADSparameter(tuple):
    """
    Create new instance of ADSparameter(A, B, C, D, E, F, DMAX)"""

    A: _Alias = ...
    B: _Alias = ...
    C: _Alias = ...
    D: _Alias = ...
    DMAX: _Alias = ...
    E: _Alias = ...
    F: _Alias = ...
    DMAX: _Alias = ...

WEIGHT_MAX: Incomplete
WEIGHT_MEAN: Incomplete
WEIGHT_NONE: Incomplete
AliphaticRings: Incomplete
AcceptorSmarts: Incomplete
Acceptors: Incomplete
StructuralAlertSmarts: Incomplete
StructuralAlerts: Incomplete
adsParameters: Incomplete

def ads(self, x, adsParameter):
    """
    ADS function"""
    ...

def default(self, mol):
    """
    Calculates the QED descriptor using average descriptor weights."""
    ...

def properties(self, mol):
    """
    Calculates the properties that are required to calculate the QED descriptor."""
    ...

def qed(
    self,
    mol,
    w=QEDproperties(
        MW=0.66,
        ALOGP=0.46,
        HBA=0.05,
        HBD=0.61,
        PSA=0.06,
        ROTB=0.65,
        AROM=0.48,
        ALERTS=0.95,
    ),
    qedProperties=None,
):
    """
    Calculate the weighted sum of ADS mapped properties
    some examples from the QED paper, reference values from Peter G’s original implementation
    >>> m = Chem.MolFromSmiles(‘N=C(CCSCc1csc(N=C(N)N)n1)NS(N)(=O)=O’)
    >>> qed(m)
    0.253…
    >>> m = Chem.MolFromSmiles(‘CNC(=NCCSCc1nc[nH]c1C)NC#N’)
    >>> qed(m)
    0.234…
    >>> m = Chem.MolFromSmiles(‘CCCCCNC(=N)NN=Cc1c[nH]c2ccc(CO)cc12’)
    >>> qed(m)
    0.234…"""
    ...

def weights_max(self, mol):
    """
    Calculates the QED descriptor using maximal descriptor weights."""
    ...

def weights_mean(self, mol):
    """
    Calculates the QED descriptor using average descriptor weights."""
    ...

def weights_none(self, mol):
    """
    Calculates the QED descriptor using unit weights."""
    ...

def default(self, mol):
    """
    Calculates the QED descriptor using average descriptor weights."""
    ...
