"""
rdkit.Chem.fmcs.fmcs module¶
FMCS - Find Maximum Common Substructure
This software finds the maximum common substructure of a set of
structures and reports it as a SMARTS strings.
This implements what I think is a new algorithm for the MCS problem.
The core description is:

best_substructure = None
pick one structure as the query, and other as the targets
for each substructure in the query graph:

convert it to a SMARTS string based on the desired match properties
if the SMARTS pattern exists in all of the targets:

then this is a common substructure
keep track of the maximum such common structure,

The SMARTS string depends on the desired match properties. For
example, if ring atoms are only allowed to match ring atoms then an
aliphatic ring carbon in the query is converted to the SMARTS “[C;R]”,
and the double-bond ring bond converted to “=;@” while the respectice
chain-only version are “[C;!R]” and “=;!@”.
The algorithm I outlined earlier will usually take a long time. There
are several ways to speed it up.
== Bond elimination ==
As the first step, remove bonds which obviously cannot be part of the
MCS.
This requires atom and bond type information, which I store as SMARTS
patterns. A bond can only be in the MCS if its canonical bond type is
present in all of the structures. A bond type is string made of the
SMARTS for one atom, the SMARTS for the bond, and the SMARTS for the
other atom. The canonical bond type is the lexographically smaller of
the two possible bond types for a bond.
The atom and bond SMARTS depend on the type comparison used.
The “ring-matches-ring-only” option adds an “@” or “!@” to the bond
SMARTS, so that the canonical bondtype for “C-C” becomes [#6]-@[#6] or
[#6]-!@[#6] if the bond is in a ring or not in a ring, and if atoms
are compared by element and bonds are compared by bondtype. (This
option does not add “R” or “!R” to the atom SMARTS because there
should be a single bond in the MCS of c1ccccc1O and CO.)
The result of all of this atom and bond typing is a “TypedMolecule”
for each input structure.
I then find which canonical bondtypes are present in all of the
structures. I convert each TypedMolecule into a
FragmentedTypedMolecule which has the same atom information but only
those bonds whose bondtypes are in all of the structures. This can
break a structure into multiple, disconnected fragments, hence the
name.
(BTW, I would like to use the fragmented molecules as the targets
because I think the SMARTS match would go faster, but the RDKit SMARTS
matcher doesn’t like them. I think it’s because the new molecule
hasn’t been sanitized and the underlying data structure the ring
information doesn’t exist. Instead, I use the input structures for the
SMARTS match.)
== Use the structure with the smallest largest fragment as the query ==
== and sort the targets by the smallest largest fragment             ==
I pick one of the FragmentedTypedMolecule instances as the source of
substructure enumeration. Which one?
My heuristic is to use the one with the smallest largest fragment.
Hopefully it produces the least number of subgraphs, but that’s also
related to the number of rings, so a large linear graph will product
fewer subgraphs than a small fused ring system. I don’t know how to
quantify that.
For each of the fragmented structures, I find the number of atoms in
the fragment with the most atoms, and I find the number of bonds in
the fragment with the most bonds. These might not be the same
fragment.
I sort the input structures by the number of bonds in the largest
fragment, with ties broken first on the number of atoms, and then on
the input order. The smallest such structure is the query structure,
and the remaining are the targets.
== Use a breadth-first search and a priority queue to    ==
== enumerate the fragment subgraphs                      ==
I extract each of the fragments from the FragmentedTypedMolecule into
a TypedFragment, which I use to make an EnumerationMolecule. An
enumeration molecule contains a pair of directed edges for each atom,
which simplifies the enumeration algorithm.
The enumeration algorithm is based around growing a seed. A seed
contains the current subgraph atoms and bonds as well as an exclusion
set of bonds which cannot be used for future grown. The initial seed
is the first bond in the fragment, which may potentially grow to use
the entire fragment. The second seed is the second bond in the
fragment, which is excluded from using the first bond in future
growth. The third seed starts from the third bond, which may not use
the first or second bonds during growth, and so on.
A seed can grow along bonds connected to an atom in the seed but which
aren’t already in the seed and aren’t in the set of excluded bonds for
the seed. If there are no such bonds then subgraph enumeration ends
for this fragment. Given N bonds there are 2**N-1 possible ways to
grow, which is just the powerset of the available bonds, excluding the
no-growth case.
This breadth-first growth takes into account all possibilties of using
the available N bonds so all of those bonds are added to the exclusion
set of the newly expanded subgraphs.
For performance reasons, the bonds used for growth are separated into
‘internal’ bonds, which connect two atoms already in the subgraph, and
‘external’ bonds, which lead outwards to an atom not already in the
subgraph.
Each seed growth can add from 0 to N new atoms and bonds. The goal is
to maximize the subgraph size so the seeds are stored in a priority
queue, ranked so the seed with the most bonds is processed first. This
turns the enumeration into something more like a depth-first search.
== Prune seeds which aren’t found in all of the structures ==
At each stage of seed growth I check that the new seed exists in all
of the original structures. (Well, all except the one which I
enumerate over in the first place; by definition that one will match.)
If it doesn’t match then there’s no reason to include this seed or any
larger seeds made from it.
The check is easy; I turn the subgraph into its corresponding SMARTS
string and use RDKit’s normal SMARTS matcher to test for a match.
There are three ways to generate a SMARTS string: 1) arbitrary, 2)
canonical, 3) hybrid.
I have not tested #1. During most of the development I assumed that
SMARTS matches across a few hundred structures would be slow, so that
the best solution is to generate a canonical SMARTS and cache the
match information.
Well, it turns out that my canonical SMARTS match code takes up most
of the FMCS run-time. If I drop the canonicalization step then the
code averages about 5-10% faster. This isn’t the same as #1 - I still
do the initial atom assignment based on its neighborhood, which is
like a circular fingerprint of size 2 and usually gives a consistent
SMARTS pattern, which I can then cache.
However, there are times when the non-canonical SMARTS code is slower.
Obviously one is if there are a lot of structures, and another if is
there is a lot of symmetry. I’m still working on characterizing this.
== Maximize atoms? or bonds? ==
The above algorithm enumerates all subgraphs of the query and
identifies those subgraphs which are common to all input structures.
It’s trivial then to keep track of the current “best” subgraph, which
can defined as having the subgraph with the most atoms, or the most
bonds. Both of those options are implemented.
It would not be hard to keep track of all other subgraphs which are
the same size.
== –complete-ring-only implementation ==
The “complete ring only” option is implemented by first enabling the
“ring-matches-ring-only” option, as otherwise it doesn’t make sense.
Second, in order to be a “best” subgraph, all bonds in the subgraph
which are ring bonds in the original molecule must also be in a ring
in the subgraph. This is handled as a post-processing step.
(Note: some possible optimizations, like removing ring bonds from
structure fragments which are not in a ring, are not yet implemented.)
== Prune seeds which have no potential for growing large enough  ==
Given a seed, its set of edges available for growth, and the set of
excluded bonds, figure out the maximum possible growth for the seed.
If this maximum possible is less than the current best subgraph then
prune.
This requires a graph search, currently done in Python, which is a bit
expensive. To speed things up, I precompute some edge information.
That is, if I know that a given bond is a chain bond (not in a ring)
then I can calculate the maximum number of atoms and bonds for seed
growth along that bond, in either direction. However, precomputation
doesn’t take into account the excluded bonds, so after a while the
predicted value is too high.
Again, I’m still working on characterizing this, and an implementation
in C++ would have different tradeoffs.
"""
from collections.abc import Generator
from typing import Any, NamedTuple, _Alias

from _typeshed import Incomplete
from rdkit import Chem as Chem

class Atom(tuple):
    """
    Create new instance of Atom(real_atom, atom_smarts, bond_indices, is_in_ring)"""

    real_atom: _Alias = ...
    atom_smarts: _Alias = ...
    bond_indices: _Alias = ...
    is_in_ring: _Alias = ...
    real_atom: _Alias = ...

class AtomSmartsNoAromaticity(dict):
    ...

    def __missing__(self, eleno): ...

class Bond(tuple):
    """
    Create new instance of Bond(real_bond, bond_smarts, canonical_bondtype, atom_indices, is_in_ring)
    """

    atom_indices: _Alias = ...
    real_bond: _Alias = ...
    bond_smarts: _Alias = ...
    canonical_bondtype: _Alias = ...
    atom_indices: _Alias = ...
    is_in_ring: _Alias = ...
    real_bond: _Alias = ...

class CachingTargetsMatcher(dict):
    targets: Incomplete
    required_match_count: Incomplete

    def __init__(
        self, targets, required_match_count: Incomplete | None = ...
    ) -> None: ...
    def shift_targets(self): ...
    def __missing__(self, smarts): ...

class CangenNode(object):
    atom_smarts: Any = ...
    index: Any = ...
    atom_smarts: Any = ...
    value: Any = ...
    neighbors: Any = ...
    outgoing_edges: Any = ...
    rank: Any = ...
    value: Any = ...
    outgoing_edges: Any = ...

    def __init__(self, index, atom_smarts) -> None: ...

class Default(object):
    timeout: None = ...
    timeoutString: str = ...
    maximize: str = ...
    atomCompare: str = ...
    bondCompare: str = ...
    completeRingsOnly: bool = ...
    matchValences: bool = ...
    maximize: str = ...
    ringMatchesRingOnly: bool = ...
    timeout: None = ...
    timeoutString: str = ...
    completeRingsOnly: bool = ...

class DirectedEdge(tuple):
    """
    Create new instance of DirectedEdge(bond_index, end_atom_index)"""

    bond_index: _Alias = ...
    end_atom_index: _Alias = ...

class FragmentedTypedMolecule(object):
    ...
    rdmol: Incomplete
    rdmol_atoms: Incomplete
    orig_atoms: Incomplete
    orig_bonds: Incomplete
    atom_smarts_types: Incomplete
    bond_smarts_types: Incomplete
    canonical_bondtypes: Incomplete

    def __init__(
        self,
        rdmol,
        rdmol_atoms,
        orig_atoms,
        orig_bonds,
        atom_smarts_types,
        bond_smarts_types,
        canonical_bondtypes,
    ) -> None: ...

class MCSResult(object):
    ...
    num_atoms: Incomplete
    num_bonds: Incomplete
    smarts: Incomplete
    completed: Incomplete

    def __init__(self, num_atoms, num_bonds, smarts, completed) -> None: ...
    def __nonzero__(self): ...

class OutgoingEdge(tuple):
    """
    Create new instance of OutgoingEdge(from_atom_index, bond_index, bond_smarts, other_node_idx, other_node)
    """

    from_atom_index: _Alias = ...
    bond_index: _Alias = ...
    bond_smarts: _Alias = ...
    from_atom_index: _Alias = ...
    other_node: _Alias = ...
    other_node_idx: _Alias = ...
    other_node: _Alias = ...

class SingleBestAtoms(_SingleBest):
    def add_new_match(self, subgraph, mol, smarts): ...

class SingleBestAtomsCompleteRingsOnly(_SingleBest):
    def add_new_match(self, subgraph, mol, smarts): ...

class SingleBestBonds(_SingleBest):
    def add_new_match(self, subgraph, mol, smarts): ...

class SingleBestBondsCompleteRingsOnly(_SingleBest):
    def add_new_match(self, subgraph, mol, smarts): ...

class Subgraph(tuple):
    """
    Create new instance of Subgraph(atom_indices, bond_indices)"""

    atom_indices: _Alias = ...
    bond_indices: _Alias = ...

class Timer(object):
    mark_times: Incomplete

    def __init__(self) -> None: ...
    def mark(self, name): ...

class TypedFragment(object):
    ...
    rdmol: Incomplete
    orig_atoms: Incomplete
    orig_bonds: Incomplete
    atom_smarts_types: Incomplete
    bond_smarts_types: Incomplete
    canonical_bondtypes: Incomplete

    def __init__(
        self,
        rdmol,
        orig_atoms,
        orig_bonds,
        atom_smarts_types,
        bond_smarts_types,
        canonical_bondtypes,
    ) -> None: ...

class TypedMolecule(object):
    ...
    rdmol: Incomplete
    rdmol_atoms: Incomplete
    rdmol_bonds: Incomplete
    atom_smarts_types: Incomplete
    bond_smarts_types: Incomplete
    canonical_bondtypes: Incomplete

    def __init__(
        self,
        rdmol,
        rdmol_atoms,
        rdmol_bonds,
        atom_smarts_types,
        bond_smarts_types,
        canonical_bondtypes,
    ) -> None: ...

class Uniquer(dict):
    ...
    counter: Incomplete

    def __init__(self) -> None: ...
    def __missing__(self, key): ...

class VerboseCachingTargetsMatcher(object):
    def report(self): ...
    targets: Incomplete
    cache: Incomplete
    required_match_count: Incomplete
    num_lookups: int
    num_search_true: int

    def __init__(
        self, targets, required_match_count: Incomplete | None = ...
    ) -> None: ...
    def shift_targets(self): ...
    def __getitem__(self, smarts, missing=...): ...
    def report(self): ...

class VerboseHeapOps(object):
    def heappop(self, seeds): ...
    num_seeds_added: int
    num_seeds_processed: int
    verboseDelay: Incomplete
    trigger: Incomplete

    def __init__(self, trigger, verboseDelay) -> None: ...
    def heappush(self, seeds, item): ...
    def report(self): ...
    def heappop(self, seeds): ...
    def trigger_report(self): ...
    def report(self): ...

class starting_from(object):
    ...
    left: Incomplete

    def __init__(self, left) -> None: ...
    def __contains__(self, value) -> bool: ...

def MATCH(self, mol, pat): ...
def all_subgraph_extensions(
    self,
    enumeration_mol,
    subgraph,
    visited_bond_indices,
    internal_bonds,
    external_edges,
): ...
def assign_isotopes_from_class_tag(self, mol, atom_class_tag): ...

class AtomSmartsNoAromaticity(dict):
    ...

    def __missing__(self, eleno): ...

def atom_typer_any(self, atoms): ...
def atom_typer_elements(self, atoms): ...
def atom_typer_isotopes(self, atoms): ...
def bond_typer_any(self, bonds): ...
def bond_typer_bondtypes(self, bonds): ...
def canon(self, cangen_nodes): ...
def check_completeRingsOnly(self, smarts, subgraph, enumeration_mol): ...
def compute_mcs(
    self,
    fragmented_mols,
    typed_mols,
    minNumAtoms,
    threshold_count=None,
    maximize="bonds",
    completeRingsOnly=False,
    timeout=None,
    timer=None,
    verbose=False,
    verboseDelay=1.0,
): ...
def convert_input_to_typed_molecules(
    self, mols, atom_typer, bond_typer, matchValences, ringMatchesRingOnly
): ...

atom_typers: Incomplete
bond_typers: Incomplete

def default_atom_typer(self, atoms): ...
def default_bond_typer(self, bonds): ...
def enumerate_subgraphs(
    self,
    enumeration_mols,
    prune,
    atom_assignment,
    matches_all_targets,
    hits,
    timeout,
    heappush,
    heappop,
): ...
def find_duplicates(self, cangen_nodes, start, end): ...
def find_extension_size(
    self, enumeration_mol, known_atoms, exclude_bonds, directed_edges
): ...
def find_extensions(self, atom_indices, visited_bond_indices, directed_edges): ...
def find_upper_fragment_size_limits(self, rdmol, atoms): ...
def fmcs(
    self,
    mols,
    minNumAtoms=2,
    maximize="bonds",
    atomCompare="elements",
    bondCompare="bondtypes",
    threshold=1.0,
    matchValences=False,
    ringMatchesRingOnly=False,
    completeRingsOnly=False,
    timeout=None,
    times=None,
    verbose=False,
    verboseDelay=1.0,
): ...
def fragmented_mol_to_enumeration_mols(self, typed_mol, minNumAtoms=2): ...
def gen_primes(self): ...
def generate_smarts(self, cangen_nodes): ...
def get_canonical_bondtype_counts(self, typed_mols): ...
def get_canonical_bondtypes(
    self, rdmol, bonds, atom_smarts_types, bond_smarts_types
): ...
def get_closure_label(self, bond_smarts, closure): ...
def get_counts(self, it): ...
def get_initial_cangen_nodes(
    self, subgraph, enumeration_mol, atom_assignment, do_initial_assignment=True
): ...
def get_isotopes(self, mol): ...
def set_isotopes(self, mol, isotopes): ...
def save_isotopes(self, mol, isotopes): ...
def save_atom_classes(self, mol, atom_classes): ...
def get_selected_atom_classes(self, mol, atom_indices): ...
def get_specified_types(self, rdmol, atom_types, ringMatchesRingOnly): ...
def get_typed_fragment(self, typed_mol, atom_indices): ...
def restore_isotopes(self, mol): ...
def assign_isotopes_from_class_tag(self, mol, atom_class_tag): ...

class TypedMolecule(object):
    ...
    rdmol: Incomplete
    rdmol_atoms: Incomplete
    rdmol_bonds: Incomplete
    atom_smarts_types: Incomplete
    bond_smarts_types: Incomplete
    canonical_bondtypes: Incomplete

    def __init__(
        self,
        rdmol,
        rdmol_atoms,
        rdmol_bonds,
        atom_smarts_types,
        bond_smarts_types,
        canonical_bondtypes,
    ) -> None: ...

class FragmentedTypedMolecule(object):
    ...
    rdmol: Incomplete
    rdmol_atoms: Incomplete
    orig_atoms: Incomplete
    orig_bonds: Incomplete
    atom_smarts_types: Incomplete
    bond_smarts_types: Incomplete
    canonical_bondtypes: Incomplete

    def __init__(
        self,
        rdmol,
        rdmol_atoms,
        orig_atoms,
        orig_bonds,
        atom_smarts_types,
        bond_smarts_types,
        canonical_bondtypes,
    ) -> None: ...

class TypedFragment(object):
    ...
    rdmol: Incomplete
    orig_atoms: Incomplete
    orig_bonds: Incomplete
    atom_smarts_types: Incomplete
    bond_smarts_types: Incomplete
    canonical_bondtypes: Incomplete

    def __init__(
        self,
        rdmol,
        orig_atoms,
        orig_bonds,
        atom_smarts_types,
        bond_smarts_types,
        canonical_bondtypes,
    ) -> None: ...

def get_canonical_bondtypes(
    self, rdmol, bonds, atom_smarts_types, bond_smarts_types
): ...
def get_typed_molecule(
    self, rdmol, atom_typer, bond_typer, matchValences=False, ringMatchesRingOnly=False
): ...
def get_specified_types(self, rdmol, atom_types, ringMatchesRingOnly): ...
def convert_input_to_typed_molecules(
    self, mols, atom_typer, bond_typer, matchValences, ringMatchesRingOnly
): ...
def get_counts(self, it): ...
def intersect_counts(self, counts1, counts2): ...
def main(self, args=None): ...
def make_arbitrary_smarts(self, subgraph, enumeration_mol, atom_assignment): ...
def get_canonical_bondtype_counts(self, typed_mols): ...
def remove_unknown_bondtypes(self, typed_mol, supported_canonical_bondtypes): ...
def find_upper_fragment_size_limits(self, rdmol, atoms): ...

class EnumerationMolecule(NamedTuple):
    rdmol: Incomplete
    atoms: Incomplete
    bonds: Incomplete
    directed_edges: Incomplete

class Atom(tuple):
    """
    Create new instance of Atom(real_atom, atom_smarts, bond_indices, is_in_ring)"""

    real_atom: _Alias = ...
    atom_smarts: _Alias = ...
    bond_indices: _Alias = ...
    is_in_ring: _Alias = ...
    real_atom: _Alias = ...

class Bond(tuple):
    """
    Create new instance of Bond(real_bond, bond_smarts, canonical_bondtype, atom_indices, is_in_ring)
    """

    atom_indices: _Alias = ...
    real_bond: _Alias = ...
    bond_smarts: _Alias = ...
    canonical_bondtype: _Alias = ...
    atom_indices: _Alias = ...
    is_in_ring: _Alias = ...
    real_bond: _Alias = ...

class DirectedEdge(tuple):
    """
    Create new instance of DirectedEdge(bond_index, end_atom_index)"""

    bond_index: _Alias = ...
    end_atom_index: _Alias = ...

class Subgraph(tuple):
    """
    Create new instance of Subgraph(atom_indices, bond_indices)"""

    atom_indices: _Alias = ...
    bond_indices: _Alias = ...

def get_typed_fragment(self, typed_mol, atom_indices): ...
def fragmented_mol_to_enumeration_mols(self, typed_mol, minNumAtoms=2): ...
def gen_primes(self): ...

class CangenNode(object):
    atom_smarts: Any = ...
    index: Any = ...
    atom_smarts: Any = ...
    value: Any = ...
    neighbors: Any = ...
    outgoing_edges: Any = ...
    rank: Any = ...
    value: Any = ...
    outgoing_edges: Any = ...

    def __init__(self, index, atom_smarts) -> None: ...

class OutgoingEdge(tuple):
    """
    Create new instance of OutgoingEdge(from_atom_index, bond_index, bond_smarts, other_node_idx, other_node)
    """

    from_atom_index: _Alias = ...
    bond_index: _Alias = ...
    bond_smarts: _Alias = ...
    from_atom_index: _Alias = ...
    other_node: _Alias = ...
    other_node_idx: _Alias = ...
    other_node: _Alias = ...

def get_initial_cangen_nodes(
    self, subgraph, enumeration_mol, atom_assignment, do_initial_assignment=True
): ...
def rerank(self, cangen_nodes): ...
def find_duplicates(self, cangen_nodes, start, end): ...
def canon(self, cangen_nodes): ...
def get_closure_label(self, bond_smarts, closure): ...
def generate_smarts(self, cangen_nodes): ...
def make_canonical_smarts(self, subgraph, enumeration_mol, atom_assignment): ...
def make_complete_sdf(self, mcs, mol, subgraph, args): ...
def make_fragment_sdf(self, mcs, mol, subgraph, args): ...
def make_arbitrary_smarts(self, subgraph, enumeration_mol, atom_assignment): ...
def powerset(self, x: list[int]): ...
def nonempty_powerset(self, x: list[int]): ...
def tiebreaker(self): ...
def find_extensions(self, atom_indices, visited_bond_indices, directed_edges): ...
def all_subgraph_extensions(
    self,
    enumeration_mol,
    subgraph,
    visited_bond_indices,
    internal_bonds,
    external_edges,
): ...
def find_extension_size(
    self, enumeration_mol, known_atoms, exclude_bonds, directed_edges
): ...

class CachingTargetsMatcher(dict):
    targets: Incomplete
    required_match_count: Incomplete

    def __init__(
        self, targets, required_match_count: Incomplete | None = ...
    ) -> None: ...
    def shift_targets(self): ...
    def __missing__(self, smarts): ...

class VerboseCachingTargetsMatcher(object):
    def report(self): ...
    targets: Incomplete
    cache: Incomplete
    required_match_count: Incomplete
    num_lookups: int
    num_search_true: int

    def __init__(
        self, targets, required_match_count: Incomplete | None = ...
    ) -> None: ...
    def shift_targets(self): ...
    def __getitem__(self, smarts, missing=...): ...
    def report(self): ...

def prune_maximize_bonds(
    self, subgraph, mol, num_remaining_atoms, num_remaining_bonds, best_sizes
): ...
def prune_maximize_atoms(
    self, subgraph, mol, num_remaining_atoms, num_remaining_bonds, best_sizes
): ...

class _SingleBest:
    best_num_atoms: int
    best_smarts: Incomplete
    sizes: Incomplete
    timer: Incomplete
    verbose: Incomplete

    def __init__(self, timer, verbose) -> None: ...
    def get_result(self, completed): ...

class MCSResult(object):
    ...
    num_atoms: Incomplete
    num_bonds: Incomplete
    smarts: Incomplete
    completed: Incomplete

    def __init__(self, num_atoms, num_bonds, smarts, completed) -> None: ...
    def __nonzero__(self): ...

class SingleBestAtoms(_SingleBest):
    def add_new_match(self, subgraph, mol, smarts): ...

class SingleBestBonds(_SingleBest):
    def add_new_match(self, subgraph, mol, smarts): ...

def check_completeRingsOnly(self, smarts, subgraph, enumeration_mol): ...

class SingleBestAtomsCompleteRingsOnly(_SingleBest):
    def add_new_match(self, subgraph, mol, smarts): ...

class SingleBestBondsCompleteRingsOnly(_SingleBest):
    def add_new_match(self, subgraph, mol, smarts): ...

def enumerate_subgraphs(
    self,
    enumeration_mols,
    prune,
    atom_assignment,
    matches_all_targets,
    hits,
    timeout,
    heappush,
    heappop,
): ...

class Uniquer(dict):
    ...
    counter: Incomplete

    def __init__(self) -> None: ...
    def __missing__(self, key): ...

def MATCH(self, mol, pat): ...

class VerboseHeapOps(object):
    def heappop(self, seeds): ...
    num_seeds_added: int
    num_seeds_processed: int
    verboseDelay: Incomplete
    trigger: Incomplete

    def __init__(self, trigger, verboseDelay) -> None: ...
    def heappush(self, seeds, item): ...
    def report(self): ...
    def heappop(self, seeds): ...
    def trigger_report(self): ...
    def report(self): ...

def compute_mcs(
    self,
    fragmented_mols,
    typed_mols,
    minNumAtoms,
    threshold_count=None,
    maximize="bonds",
    completeRingsOnly=False,
    timeout=None,
    timer=None,
    verbose=False,
    verboseDelay=1.0,
): ...

class Timer(object):
    mark_times: Incomplete

    def __init__(self) -> None: ...
    def mark(self, name): ...

def fmcs(
    self,
    mols,
    minNumAtoms=2,
    maximize="bonds",
    atomCompare="elements",
    bondCompare="bondtypes",
    threshold=1.0,
    matchValences=False,
    ringMatchesRingOnly=False,
    completeRingsOnly=False,
    timeout=None,
    times=None,
    verbose=False,
    verboseDelay=1.0,
): ...
def subgraph_to_fragment(self, mol, subgraph): ...
def make_fragment_smiles(self, mcs, mol, subgraph, args=None): ...
def make_fragment_sdf(self, mcs, mol, subgraph, args): ...
def make_complete_sdf(self, mcs, mol, subgraph, args): ...

structure_format_functions: Incomplete

def make_structure_format(self, format_name, mcs, mol, subgraph, args): ...
def nonempty_powerset(self, x: list[int]): ...
def parse_num_atoms(self, s): ...
def parse_select(self, s): ...
def parse_threshold(self, s): ...
def parse_timeout(self, s): ...
def powerset(self, x: list[int]): ...
def prune_maximize_atoms(
    self, subgraph, mol, num_remaining_atoms, num_remaining_bonds, best_sizes
): ...
def prune_maximize_bonds(
    self, subgraph, mol, num_remaining_atoms, num_remaining_bonds, best_sizes
): ...
def remove_unknown_bondtypes(self, typed_mol, supported_canonical_bondtypes): ...
def rerank(self, cangen_nodes): ...
def restore_isotopes(self, mol): ...
def save_atom_classes(self, mol, atom_classes): ...
def save_isotopes(self, mol, isotopes): ...
def set_isotopes(self, mol, isotopes): ...
def subgraph_to_fragment(self, mol, subgraph): ...
def tiebreaker(self): ...

class starting_from(object):
    ...
    left: Incomplete

    def __init__(self, left) -> None: ...
    def __contains__(self, value) -> bool: ...

range_pat: Incomplete
value_pat: Incomplete

def parse_select(self, s): ...

compare_shortcuts: Incomplete

def main(self, args=None): ...
