"""
rdkit.Chem.MolDb.FingerprintUtils module¶
"""
from _typeshed import Incomplete
from rdkit import Chem as Chem
from rdkit import DataStructs as DataStructs

similarityMethods: Incomplete
supportedSimilarityMethods: Incomplete

class LayeredOptions(object):
    fpSize: int = ...
    loadLayerFlags: int = ...
    maxPath: int = ...
    minPath: int = ...
    nWords: int = ...
    searchLayerFlags: int = ...
    minPath: int = ...
    maxPath: int = ...
    fpSize: int = ...
    wordSize: int = ...
    nWords: int = ...

    def GetFingerprint(self, mol, query=True): ...
    def GetQueryText(self, mol, query=True): ...
    def GetWords(self, mol, query=True): ...
    def GetQueryText(self, mol, query=True): ...

def BuildAtomPairFP(self, mol): ...
def BuildAvalonFP(self, mol, smiles=None): ...
def BuildMorganFP(self, mol): ...
def BuildPharm2DFP(self, mol): ...
def BuildRDKitFP(self, mol): ...
def BuildSigFactory(
    self,
    options=None,
    fdefFile=None,
    bins=[(2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 100)],
    skipFeats=("LumpedHydrophobe", "ZnBinder"),
): ...
def BuildAtomPairFP(self, mol): ...
def BuildTorsionsFP(self, mol): ...
def BuildRDKitFP(self, mol): ...
def BuildPharm2DFP(self, mol): ...
def BuildMorganFP(self, mol): ...
def BuildAvalonFP(self, mol, smiles=None): ...
def DepickleFP(self, pkl, similarityMethod): ...
